version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/ui/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/api/'
    schedule:
      interval: 'daily'
