ignore:
  - package:
      # https://nvd.nist.gov/vuln/detail/CVE-2001-1274
      name: mysql
      version: 2.18.1
  - package:
      # https://nvd.nist.gov/vuln/detail/CVE-2017-18589
      # I'm not placing in high values for ages
      name: cookie
      version: 0.5.0
  - package:
      # https://nvd.nist.gov/vuln/detail/CVE-2021-27478
      name: opener
      version: 1.5.2
