version: '3'
services:
  mysql:
    build:
      context: sql
      dockerfile: Dockerfile
    #    command: "bash -c './setup-database.sh'"
    container_name: seconds_mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    environment:
      TZ: "America/New_York"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: seconds_api
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      API_PORT: ${API_PORT}
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    container_name: seconds_ui
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    links:
      - api
    environment:
      API_PORT: ${API_PORT}
volumes:
  mysql: