# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Branch CI for API

on: [ push ]

jobs:
  api:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node ☕
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install 🔧
        run: cd api; npm ci

      - name: Lint 🔍
        run: cd api; npm run lint

      - name: Unit Test 🤞
        run: cd api; npm run test

      - name: Dependency Check 🐛
        run: cd api; npm run owasp
